package com.sivgos.assamquizforapsc;

public class QuestionDatabase {
    public String mQuestions [] = {
            "Who is the founder of South-East Asia Ramayana Research Centre?",
            "Who is the recipient of Dr. Bhupen Hazarika International Solidarity Award in 2015?",
            "Who is the first Assamese woman to be awarded Sangeet Natak Academy Award?",
            "In which division of British Indian Army, Mangal Pandey was inducted as a soldier?",
            "India's average annual growth rate of population during 2001-2011 was",
            "In which sector, maximum allocation and priorities were given in the 12th five year plan in Assam?",
            "The contribution of agriculture India's Gross Domestic Product (GDP) is",
            "Who among the following has been crowned Miss Universe in 2017?",
            "Which of the following awards is not associated with the field of sports?",
            "B.K.S. Ayenger is related to the field of",
            "Namdang Silsako - a 60 meter long stone bridge constructed in 1703 during the reign of Rudra Singha is still serving as an important bridge on",
            "The unified National Calender of India is based on Saka Era and it is behind the internationally followed Gregorian calender by",
            "India's spectacular achievements in oilseeds production has been called",
            "The Rowlatt Act aimed at",
            "Who among the following is known as the 'Nero of the Deccan'?",
            "'Titanic' the great ocean linker sank in the year",
            "Who among the following described Indians as 'Hot tempered but honest'?",
            "AGMARK is",
            "'Vedaranyam March' was a part of the",
            "After the Bardoli Satyagrah, the title of 'Sardar' to Vallabhbhai Patel was given by",
            "International Day of Disabled Personsn is celebrated on",
            "Which of the following countries is the biggest producer of carbon dioxide?",
            "India's first Interactive Educational Channel is named",
            "Which of the following railway stations has all the three Gauges?",
            "Nobel Prize is not awarded in the field of",
            "Which of the following countries has the greatest number of cars per mile of road?",
            "What does the abbreviation E.C.G. stand for?",
            "Which of the following is the only Asian country to be a member of G-8?",
            "The distribution of power between the center and the states in the Indian constitution is based on the sceheme provided in the",
            "The people of India were referred to as 'Hindu' first by",
            "The Himalayas are formed of parallel fold ranges of which the oldest range is the",
            "The only anthropoid ape to be found in India is the",
            "The name of poet Kalidasa is mentioned in the",
            "Who among the following is known for his work on medicine during Gupta periods?",
            "The famous teacher of Naland on whose request and advice, Chinese pilgrim Hiuen Tsang visited Kamrup was",
            "During calamities and lean times, long Haired Assamese woman dance in circles to the beat of bamboo sticks struck against conch-shells and bangles. The ritual is known as",
            "Name the famous pass along Indo-Myanmar border through which successive generation of Mongoloid people entered India.",
            "In which of the following districts, Sital Patti, a type of mat traditionally manufactured?",
            "Hema Sarasvati and Harihar Vipra enjoyed the patronage of",
            "Madhavadeva was educated in the school at Banduka maintained and taught by",
            "'Diamond ring' is a phenomenon observed",
            "Seasonal variation is the least",
            "Canal irrigation is most important in North East India because",
            "PH Value is indicative of",
            "Which of the following straits separate North America from Asia",
            "Which of the following is used as an explosive?",
            "Which of the followings is known as Hunter's paradise?",
            "The parliament of Isreal is known as",
            "In India the major export of Iron ore is from",
            "The Assam Sahitya Sabha came to be known by its present name only after its registration on May'5 1924 at Jorhat. By what name was it known earlier?",
            "1 Bigha land is equal to",
            "The only National Institute of Technology in Assam is located at",
            "In which of the following districts, the area under irrigation is highest?",
            "Who among the following is the author of the book 'Assamese: Its formation and development'?",
            "The constitution of India has laid down that the two Houses of Parliament must be summoned at least",
            "What is the name of the document published by the Government to appraise the public on any issue?",
            "The Union Council of Ministers in India is appointed by",
            "No person can be employeed in factories or mines unless he is above the age of",
            "To whom are the fundamental rights under the Indian Constitution granted?",
            "Which of the following is the writ of 'habeas corpus' associated?",
            "The Pressler Amendment of the U.S. congress related to the stoppage of American aid to countries",
            "The material used in hospitals for setting the fractured bones in the right position contains",
            "Which of the following according to the Chelliah Committee Report is the best way of encouraging honesty and voluntary tax compliance?",
            "Which of the following is a leading export item among the plantation crops of India",
            "The radioactive isotope used in the treatment of cancer is",
            "Which of the following is not an indirect tax",
            "The Paichasa system of marriage will survive in Assam at least symbolically among Bodos and Kacharis. What is this system about?",
            "In what aspect is the Assamese Ramayana by Madhav Kandali unique?",
            "Under which of the following schemes of the Government of Assam senior citizens are taken to various religious places on tour?",
            "The last independent Ahom king was",
            "Who among the following national leaders of India, preached through his paper Kesari, his new ideas of self-help and national revival among the masses?",
            "Who among the following was the first leader from Assam to be selected to the Congress Working Committee?",
            "Indian Institute of Science is situated at",
            "At what temperature Fahrenheit and Centigrade scales show same reading?",
            "Among different kinds of water, which one is free from bacteria?",
            "Why does the mercury column in a barometer falls rapidly before a storm?",
            "The physical part of computer which include mechanical, electrical and electronic devices are known as",
            "Which of the following gases is present under pressure in soft drinks?",
            "The study of nervous system and its diseases is called",
            "A water tank on the top of a tall building feeds water in the taps of different floors. The water will gush out at highest speed from a tap on a floor",
            "In an examination 900 boys and 600 girls appeared. 60% of the boys and 30% of the girls passed the examination. The percentage of candidates who failed is",
            "The population of a town increases at the rate of 10% annually. The present population is 726000. The population of the town 2 years ago was.",
            "In certain code language, '746' means 'he is angry'. '63' means 'he was happy'; '324' means she is happy. Which of the following must be the code for angry?",
            "A student gets 122 and fails by 28 marks when pass mark is 40%. The maximum marks is",
            "One fifth of a number is less tha itself by 120. What is the number?",
            "If the largest three-digit number is subtracted from the smallest five-digit number, then the balance is",
            "Which of the following would have happened if the axis of the earth had not been inclined?",
            "The smallest bone of the human body is",
            "The power to declare war or conclude peace under the constitution of India is vested in",
            "India's first outcome budget was presented in the year",
            "The investment commission of India is headed by",
            "Mahatma Gandhi undertook fast unto death in 1932, mainly because",
            "The longest National Highway in India is",
            "A deadlock between Lok Sabha and Rajya Sabha calls for a joint sitting of the Parliament during the passage of",
            "The average global temperature in degrees Fahrenheit is around",
            "Who was the first Indian Governor-General?",
            "The increasing amount of carbon dioxide in the air is gradually increasing the temperature of the atmosphere, because it absorbes",
            "After whom is the National Integration Film award named?",
            "All revenue received by the Indian Government by way of taxes and other receipts for the conduct of Government business are credited to",
            "Which area in India gets the summer monsoon first?",
            "The first Gulf Country to propose votes for women is",
            "The annual financial statement is laid before the two Housed of Parliament in accordance with",
            "March 15 is celebrated as",
            "As an economy develops",
            "Foreign Direct Investment (FDI) in India has shown distict preference for",
            "Which of the following films won the best film award in the 85th Academy Award (Oscar), 2013?",
            "Brass gets discoloured in air because of the presence of which of the following gases in air?",
            "Assam University is situated at",
            "The Members of Parliament can express themselves at the Houses in",
            "The boundary between India and Pakistan is demarcated by",
            "The 17th century Mughal marvel which has been recently included in UNESCO's list of World Heritage Sites is",
            "National Science Day is observed on Feb'28, every year because on this day",
            "An agreement to suspend hostility in order to negotiate for peace is called",
            "Who among the following opposed Mahatma Gandhi's association with the Khilafat Movement?",
            "Naphaphu is a healing herb found in NE India. Its leaves have the propertyies of",
            "Which organization, concerned with International cooperation, was set up by the Bretton Woods Agreement in 1944",
            "Cocoa comes from a tropical tree 'Theobroma cacao'. From which part of the tree it is obtained?",
            "Which of the forest types are economically most exploited?",
            "Who of the following Indian Prime Ministers never faced the Parliament during his tenure?",
            "The Souther part of India is considered to be less prone to earthquakes because",
            "Which of the following is true of the International Court of Justice?",
            "Which of the following states rank first in the country in terms of Hydroelectric Power potential?",
            "Which of the following indicates the calories required by a normal generally healthy adult per day as food?",
            "Which of the following is known as the 'Fourth Estate'?",
            "The first Private College established in Assam in 1930 is",
            "Tulsidas, the author of Ramcharitmanas, was a contemporary of which of the following rullers?",
            "Madame Tussaud's Wax Museum is located in",
            "Which of the following rivers has its source of origin in Tibet?",
            "One of the occupational health hazards commonly faced by the workers of ceramics, pottery and glass industry is",
            "History speaking, the four-fold division of the society, or caste system, came into existence ",
            "Which of the following states has actually added to its existing forest cover area?",
            "Which of the following rivers of India is known as Vridh (old) Ganga",
            "Who among the following was the first Ahom ruller to accept Hinduism?",
            "The first principal of Cotton College was",
            "'Tobacco' was introduced to India in the 16th century by the",
            "What is the mosquito-driving folk festival popular in Lower Assam?",
            "Where the Dikhow river meets the Mighty Brahmaputra, stands a humble memorial of the Muslim saint Ajan Pir. Where does it stand?",
            "The purpose of Directive Principles of State Policy is to",
            "The total length of Indo-Bangladesh border is",
            "The Karakoram Pass links",
            "Which one of the followings is not a millet?",
            "The roaring forties is/are",
            "Which of the following is also known by the name Sahayadri Range?",
            "Which of the following is the largest peninsula in the world?",
            "Which of the following is the earliest stringed musical instrument of India?",
            "Which of the following countries possesses the largest number of cattle and buffaloes?",
            "What is the new name for the standard time followed all over the World?",
            "How many killoeters are represented by 1 degree of latitude?",
            "Which of the following is not a green house gas?",
            "Where in Assam would one find 'Saubhagya Kunda' which is believed to have power of cleaning the sins of anyone who bathes there?",
            "Botanists call it 'Camellia Sinensis', we call it",
            "What kind of soil is ideal for rice cultivation?",
            "When were the states of India recognised on linguistic basis?",
            "The President of India is not empowered to ",
            "In the Constitution, the word 'Cabinet' has been used only once, and it is in",
            "'Freon' used as refrigerant is chemically known as",
            "In which of the following cities, Netaji Subhash Chandra Bose  laid the foundation stone of 'Indian National Army'?",
            "Who among the following suggested the winding up of the Indian National Congress after attaining independence?",
            "Fourteenth Financial Commission has been setup by the Government of India under the Chairmanship of",
            "What is the number of M.P.'s from Assam in the Lok Sabha?",
            "Who acts as the President of India when neither the President nor the Vice President is available?",
            "Union Parliament can make laws on any subject in the State List",
            "Disagreement between the two Houses of the Indian Parliament is finally resolved by which of the following processes?",
            "Largest cellphone making company in the world is",
            "Census in India is held regularly after every",
            "Which of the following is the primary source of energy in India?",
            "The National Income in India is estimated by the",
            "Convertibility of the rupees implies",
            "Which of the follwong in planned expenditure of the Government of India?",
            "Minimum Support Price of foodgrains are ",
            "Who among the following organized the society of revolutionaries, 'Abhinav Bharat'?",
            "Which of the following upheavals took place in Bengal immediately after the Revolt of 1857?",
            "The Sothern most point of India is",
            "Who was the first Muslim Presindent of Indian National Congress?",
            "Which one of the following provided an ocassion for massive movement immediately after second World War?",
            "The non-cooperative movement was called by Mahatma Gandhi because",
            "The 'Kuka' movement was led by",
            "Who represented India in the World Congress of Religions at Chicago in 1893?",
            "Who was the president of Indian National Congress when India was free?",
            "Who composed the famous song 'Shreemoyee Asameer' which is sung when the Bihu flag is unfurled?",
            "The first state in India which has been formed on a purely linguistic basis is",
            "The process of liberalisation of Indian economy started in",
            "The old name of Odisha was",
            "Who among the following attended the Congress Session at Bombay in 1908 as the representative of the Jorhat Sarbajani Sabha?",
            "The National Highway enters Assam through two points on the Assam-West Bengal inter-state border. One point is Srirampur and the other point is",
            "Which one of the following glands controls the development of sex orgains in humans?",
            "The distance of distinct vision for a normal eye is",
            "Lime is sometimes applied with soil in order to",
            "When milk is converted into curd, the sour taste is due to",
            "What is the name of the international award presented each year by UNESCO for popularising science?",
            "Who is known as the father of medicine?",
            "The technique used to maintain the nutritive value of soil over the years is",
            "'Silviculture' relates to",
            "Anup started from his office for law and order duty. After travellimg straight for a distance of 4 km, he turned left for the market and travelled straight for 600 metres. He now turned left again and travelled straight for another 200 metres, and turned left again and travelled straight for 600 metres. How far is Anup from his office?",
            "In an election between two candidates, one got 55% of the total valid votes, 20% of the votes are invalid. If the total votes are 7,500, what is the number of valid votes the other person got?",
            "The minimum number of colors required to paint all the sides of a cube that no two adjacent faces may have the same color, is",
            "In a code language STRONGER is written as TSSNOFFQ. How FREEDOM is written in that code?",
            "Three years ago, the average age of family of 5 members was 17 years. A baby having been born, the average age of the family is same today. The present age of the baby is",
            "Five boys are sitting in a row. 'A' is on the right of 'B'. 'E' is on the left of 'B', but to the right of 'C'. If 'A' is on the left of 'D', who is sitting in the middle?",
            "'Video' is related to 'Cassette' in the same way as 'Computer' is related to",
            "In an examination 80% of the students passed in English, 75% in Assamese and 18% failed in both the subjects. If 219 candidates passed in both, find the total number of candidates who appeared who appeared the examination",
            "Who among the following attended all the three Round Table Conferences?",
            "The rate at which the Reserve Bank of India leads funds to the other commercial banks is called",
            "National voters day is celebrated every year on",
            "The only facility in India to test H5N1 variant of bird flu is the High Security Animal Disease Laboratory located at",
            "Which of the following states does not share border with Bhutan?",
            "Which is the smallest state of India in terms of area?",
            "Where are the Headquarters of Asian Development Bank?",
            "How can the International Date Line be explained in the simplest term?",
            "Which of the following is not an important factor of climate of an area?",
            "What is the unit of measurement derived from the Latin word for 'field', was initially used for the amount of land a pair of oxen can plough in a day?",
            "Safety wire used in electric circuits is made of a material having",
            "Through which of the following media does sound travel the fastest?",
            "Which of the following cities is known as the White City?",
            "Which of the following is observed as Kisan Divas (Farmer's Day)?",
            "A Black Hole is",
            "The chemical name of Baking Soda is",
            "A high sea wave resulting from earthquake is known as",
            "Sri Madhab Ddev Kalakshetra is to be set by the Government of Assam at",
            "Hugo Chavez who expired on 5 March, 2013 was the President of",
            "Which of the following films has been awarded the best feature film award in the 65th National Film Award for the year 2018?",
            "Who has been awarded the winner of fbb Colors Femina Miss India 2018?",
            "Which of the following is NOT a cash crop?",
            "The British Prime Minister, Clament Atlee, announced on February 1947 that the British would transfer power to India latest by",
            "World's largest ground based space observatory has been opened in",
            "'Ambubasi Mela' is held in the Kamakhya Temple every year in the month of",
            "The present Pope in the Roman Catholic Church, Jorge Mario Bergoglio belongs to",
            "Who among the following has been chosen for Saraswati Samman, 2017?",
            "The largest river island in the world, Majuli is believed to be formed in an earthquake. Who was the Ahom king during that period?",
            "Which one of the following vitamines is available in Rain water?",
            "Which famous comic character's former name was 'Mortimer'?",
            "Name the first Assamese Justice of the Supreme Court of India.",
            "Where and when was the first postal stamp issued in India?",
            "A game of archery played by the villagers together in Himachal Pradesh on Baisakhi days is said to date back to the Mahabharata. The game is called",
            "The 18th Summit of the Non-Aligned Movement (NAM) will be held in 2019 in which  of the following countries?",
            "The length of the Indian costline is",
            "The 32nd Summit of the Association of South East Asian Nations (ASEAN) was held in April 2018 at",
            "Which building is considered to be a replica of the famous Taj Aurangabad?",
            "Who wrote 'The peasants have to liberate themselves not only from foreign yoke but also from the yoke of landlords and capitalists'?",
            "Who among the following is famous for introducing Subsidiary Alliance System",
            "Who among the following was the first to become a Buddhist nun?",
            "Who among the following was a Sikh priest who openly preached the gospel of violent overthrow of British rule and urged the people to adopt Bande Mataram as a revolutionary salute?",
            "In which session, the National Congress decided to buycott the Simon Commission 'at every stage and in every form'?",
            "'The British empire is rotten to the core, corrupt in every direction, and tyrannical and mean.' - This was the uttarance of an European who participated in the Indian National Movement. Who was he/she?",
            "The 41st Session of the Congress was held at Pandu in December 1926. Who was the president of that session?",
            "Who among the following from Assam joined the famous Dandi March?",
            "The image of Garuda in the middle of the lintel in the temple door-frame of Da-Parvatiya proves that it was a ",
            "The first Assamese film Joymoti was made in",
            "Radiocarbon dating is used to determine the age of",
            "What was the name of India's first atomic reactor which went critical in August, 1956",
            "Which planet rotates the fastest about its axis?",
            "Which one of the following is the highest water fall in the World?",
            "The old Tibetan name of Mount Everest is",
            "Viper island is located in",
            "Out of the five stanzas of the song composed by Rabindranath Tagore, which one constitutes the National anthem of India?",
            "The world's largest volcanic centre is that of",
            "People drinking water from a shallow handpump are likely to suffer from all of the following diseases except",
            "Where is the headquarter of the Astronomical Society of India located?",
            "Local supply of coal is not available to",
            "The Tirupati Venkateshwara temple is located in",
            "Which of the following countries is the principal foreign aid donor to India?",
            "Berry White Medical School was located in",
            "The river Brahmaputra enters into the Indian territory beyond Kobo on the Mac Mohan line at",
            "At the 1910 Allahabad Congress, who moved a resolution against communal representation in the Legislative Council?",
            "The Gahbar (Garbha Griha) of the Madan Kamdev Temple, which is the only living shrine of the area, enshrines a large image of",
            "Brid flu is caused by the virus",
            "A proceeding on behalf of the aggrieved person in either the High Court or the Supreme Court for enforcement of constitutional rights, can be initiated",
            "The Lt. Governor of a Union Territory can issue an ordinance",
            "Who among the following decides about the number of Judges in a High Court?",
            "Razia Sultan, the first woman to sit on the throne of Delhi, was the daughter of",
            "Who among the following advocated 'Partyless Democracy'?",
            "The electoral college which elects the President of India consists of",
            "Delhi got National Capital Territory status in accordance with the",
            "How many standing committees concerning all the ministries and departments have been set up under the committee system adopted by the Parliament?",
            "Tamasha is a robust form of folk theatre in",
            "Which is the period of South-West monsoon in India?",
            "The rebellion (ulgulam) of the Munda tribesmen was led by",
            "The second Session of the Indian National Congress was held in Calcutta in 1886 and was presided over by Dadabhai Naoroji. How many delegates attended this meeting?",
            "The so-called 'Assam Riots' in 1893-94 was in fact",
            "The special status of Jammu and Kashmir implies that it has",
            "Why was 26th January chosen for declaration of India as a Sovereign Democratic Republic with a new constitution?",
            "Booker prize is awarded in the field of",
            "Karnam Malleswari, who became the first Indian woman ever to win an Olympic Gold medal is a/an",
            "World Environment day is celebrated on",
            "Spondylitis is the name of a disease which effects the",
            "The headquarter of Asian Development Bank (ADB) is located at",
            "The Constitution of India was enacted by the",
            "The first Statistics day was observed in 2007 on",
            "The Committee on Distribution of Income and Levels of Living, is more popularly known as",
            "Tuticorin is",
            "The accidental and health insurence scheme launched by the Assam Government is known as",
            "The headquarters of the North-Eastern Council (NEC) is at",
            "The fortress 'Simalugarh' about which the Muslim historian Shihabuddin speaks very eloquently is situated near",
            "Who among the followings met Lord Wellesley, Governor General of India, in 1806 and implored him to give her military aid to enable her to restore peace and good environment in Assam?",
            "George Smith, Frances Arnold and Greg Winter have been awarded Nobel Prize in 2018 for",
            "Who said, 'We are not Shikhs or Punjabis, our religion was Patriotism.'?",
            "The Orunodoi, the first Assamese News Paper was published from 1846 to ",
            "The Wahabi movement could not achieve the status of a national movement because",
            "The Assam association was replaced in 1921 by the",
            "A periscope works by the principle of",
            "The largest cruise ship in the world is",
            "We find as we go up the atmosphere, the heights of the various regions are in the following order",
            "The most likely period in which a woman may concieve is",
            "During dehydration, the substance that is usually lost by the body is",
            "Which chemical is added to water supply to prevent tooth decay?",
            "The plants popularly known as 'petro crops' are are rich in",
            "In a certain code, MAIN is written as IMNA and GOAL is written as AGLO. How is DUSK written in that code?",
            "At a service centre for small vehicles, a machine is able to complete washing 10 cars in 42 minutes. How many cars can the machine wash in 7 hours?",
            "When the office of the President falls vacant, the same must be filled within",
            "Prime Minister holds office in practice",
            "The cases involving the enforcement of Fundamental Rights fall under",
            "Before assuming office, the High Court Judges are administered Oath by",
            "A liquid drop tends to have a spherical shape because",
            "Which one of the following substances is released into blood stream of a normal individual following an increase in the concentration of blood sugar?",
            "The blue color of the water of the sea is due to ",
            "Which one of the following is taken by sports persons as a stimulant to enhance performance?",
            "Sakr Era is calculated from the year",
            "Shariat is the",
            "Mahenjo-Daro is known as the",
            "Who among the following is known as 'Chilarai' for skilful and swift military operation?",
            "The 'Poa Mecca' near Hajo was built in the memory of",
            "Local self governance for both cities and villages was introduced by",
            "The militant organiziation started by V.D. Savarkar in 1904 was",
            "Who among the following was known as Sher-e-Punjab?",
            "Zojila Valley connects",
            "Krishna Sobti, who has been awarded the 53rd Jnanpith Award for the year 2017 is a",
            "'Epicentre' is a term commonly associated with",
            "The wife of a Mughal Emperor, who is beleived to have subotaged the work of the rebels by acting as an informer to the British, was",
            "If India is to Pokhran, Pakistan is to what?",
            "The cooling masses of water that often follow the El Nino warming trend is known as",
            "Who among the following was the first ever Indian to be crowned as Miss Asia Pacific?",
            "India's first Arabic and Persian University was innaugurated on April 10, 1998 at",
            "What is the total length of rivers and canals in Assam?",
            "Total number of districts in Assam is",
            "In which year in India a census was taken for the entire country simultaneously for the first and from then onwards census has been consucted every ten years without a break?",
            "India's second highest civilian award in the field of Arts in 2018 was awarded to Ghulam Mustafa Khan and Ilaiyaraaja. What is the award?",
            "Which of the following methods was followed by Harappan Culture for the disposal of the dead?",
            "Which of the following occurs more frequently than the other three in the Indian ocean?",
            "By which king was the title 'Siladitya' adopted?",
            "The capital city of Ahmedabad was built by Ahmadshah on the site of the old town of",
            "Assam govt in February 2018 decided to set up 3 Terminal Mart for agricultural products at",
            "When has Armed Forces (Special Powers) Act (AFSPA) been removed from Assam, Meghalaya and parts of Arunachal Pradesh?",
            "On 3rd to 5th May 2018, ‘Vibrant North East 2018′ is held in Guwahati. The event was organised by",
            "On December 29, 2017, cargo movement on the Pandu-Dhubri route was flagged off by ",
            "Who has been appointed as the Chief De Mission for the 23rd Winter Olympic Games (WOG-2018) by the Indian Olympic Association?",
            "The fundamental Duties were incorporated in the Constitution of India by the",
            "Which of the following rullers is considered as the Shivaji of North Eastern India?",
            "Alfred Nobel is associated with the invention of",
            "The Indus valley civillization is associated with",
            "The National Human Rights Commission is a ",
            "The council of ministers has to resign if a no-confidence motion is passed by the majority members of",
            "The first Indian woman to climb the Mount Everest two times was",
            "The British Prime Minister when India got independent was",
            "Who was the surgeon who pioneered antiseptic surgery in 1865?",
            "Who is regarded as the great law-giver of ancient India?",
            "'Philology' is the study of",
            "The oldest form of composition of Hindustani Vocal Music is",
            "Which among the following is common to Buddhism and Jainism?",
            "Of the following tribal groups of India, which one is numerically the largest?",
            "Who among the following was not a member of the drafting committee of the Constitution?",
            "Which of the following warships of India has now been converted into a floating museum?",
            "Which of the following pairs are not correctly matched?",
            "Annie Besant was associated with which of the following?",
            "Who coined the Motto of Asian Games?",
            "Which one of the following is not an ASEAN member?",
            "Which of the following states was the first to adopt Panchayati Raj in India?",
            "The second battle of Panipat (1556) was fought between",
            "Which is the largest state of North-East India in terms of area?",
            "The Headquarter of United National Human Right Commission is in",
            "Former Prime Minister Lal Bahadur Shastri gave the slogan",
            "Which of the following countries share boundaries with India?",
            "The Indian President can proclaim Emergency under",
            "Where are the famous Ajanta Caves located in India?",
            "Mahatma Gandhi Setu is built over the river",
            "India leads the world in the export of",
            "Fatehpur Sikri was built by",
            "Food energy is measured in",
            "Which sportsman's birthday is celebrated as National Sports Day in India?",
            "Which of the four Vedas is the earliest text?",
            "What is India's rank in the world production of rice?",
            "The Railway System was introduced in India in",
            "Which is the biggest port in India?",
            "Consider the following foreign visitors to India:\n 1. Alberuni 2. Fa-hein 3. Hiuen Tsang 4. Megasthenes \n The correct chronological order in which these persons visited India:",
            "Which one of the following was written by Tulsidas?",
            "Who developed the World Wide Web?",
            "Who was the author of the book 'Dreams of my father'?",
            "The 'Malwa Trophy' is related to which of the following sports?",
            "At which place did Gautam Buddha delibered his first sermon?",
            "In which of the following countries would you find the world's largest Hindu Temple?",
            "Which is the first state to implement e-Cabinet solution for the state cabinet members?",
            "Who was the author of the book 'A Train to Pakistan'?",
            "In terms of economics, the recession ocurring between two times with a small gap in between is known as",
            "Which of the following day is obereved on 8th May every year?",
            "Who is the author of the book 'The Best Thing About You is You'?",
            "The Reserve Bank of India (RBI) was set up on the recommendation of",
            "The Capital of King Kanishka was",
            "Mahatma Gandhi was called 'Father of the Nation' by",
            "Purna Swaraj resolution was adopted on the banks of which river?",
            "With which dance is Birju Maharaj associated with?",
            "Who composed 'Sare Jahan se Accha'?",
            "Which movement is associated with the 1905 Bengal Partition?",
            "The Mahabalipuram Temples were built by",
            "Any dispute arising out of or in connection with the election of a President or Vice-President is inquired into",
            "The Simon Bolivar Award is given by",
            "Christopher Columbus who discovered the West Indies belonged to",
            "Jim Corbett National Park is in",
            "Muammar Gaddafi who was killed in 2011 was a political leader of",
            "'IAEA' is an organization which functions in the area of",
            "Which of the following organizations is established mainly to promote Micro, Small and Medium industrial sector in India?",
            "Who among the following is the President (Chief) of the World Bank at present?",
            "As directed by the UNSECO, the 'International Literary Day' is observed on which of the following days every year?",
            "Which of the following awards is given on exemplary contribution in the area of science and technology?",
            "Who was the founder of the Varman Dynasty? ",
            "Which is the first National Park in India?",
            "After achieving the distinction of being the first district in the country to achieve 100% literacy, which district of Kerala state is now on the way to have bank account for every adult?",
            "Between which of the following stations does the Samjhauta Express train run?",
            "Which of the following books was banned by all Muslim countries, including India?",
            "Under Articel 80 of the Constitution, how many members of the 250 members of the Upper House can be nominated by the President of India?",
            "Which body framed the Constitution of Independent India?",
            "Apart from Teachers' Day, September 5 is also observed as",
            "The story of Krishna's marriage with Rukmini is described in ______________ by Sankardev.",
            "Right of Freedom of Religion is guaranteed under the Constitution in Articles -",
            "The story of Usha's gandharva marriage with Aniruddha, the grandson of Krishna is described in ____________ by Shankardeva.",
            "Who was the first European to visit India?",
            "Which one of the following is the national aquatic animal of India?",
            "In which year Nobel Prize for Peace was awarded to the International Committee of the Red Cross?",
            "Which of the following awards is given by the government of Madhya Pradesh for excellence in the field of classical music, dance etc.",
            "The only Asian country through which the equator passes twice is?",
            "Who among the following is known as the Father of India's Nuclear Programme?",
            "The First Ammendment made in 1951 added a new schedule to the Indian Constitution. It was the ___________ schedule.",
            "What was the name of the king who shifted the capital from Pragjyotishpur to Tezpur?",
            "Which of the following countries is the world's thrid largest producer and exporter of uranium and has world's largest known reserves of uranium, amounting to 23% of the world's total reserves.",
            "Helle Thornings-Schmidt is the first woman Prime Minister of which of the following European countries?",
            "The legal adviser to a State Government is known as",
            "Who was the founder of Pala Dynasty of Assam?",
            "A.R. Rahman is not associated with which of the following movies?",
            "The World Investment Report 2018 was published recently. The report is published every year by",
            "The Five Year Plans in India are finally approved by which of the following bodies?",
            "The first Non-American to be appointed as the Director on the board of 'Bank of America' was _______",
            "Which country's Prime Minister has inaugurated the third edition of the geopolitical conference - Raisina Dialogue?",
            "Which temple of Telangana recently got ISO Certification?"
    };
    public String FirstOption[] = {
            "Late Dr. Bhupen Hazarika",
            "Shyam Benegal",
            "Sudakshina Sarma",
            "34th Bengal Native Infantry",
            "1.64%",
            "Rural Development",
            "14%",
            "Ms. Leila Lopes",
            "Arjuna Award",
            "Social Work",
            "NH-56",
            "100 years",
            "Blue revolution",
            "Compulsory economic support to war efforts",
            "Ala-ud-din",
            "1912",
            "Nikitin",
            "An improved quality of egg",
            "Temple Entry Movement",
            "C.R. Das",
            "September 3",
            "Japan",
            "Gyan Darshan",
            "Ooty",
            "Peace",
            "India",
            "Electrocardiogram",
            "India",
            "Morley-Minto Reforms",
            "The Greeks",
            "Siwalik Range",
            "Hanuman Monkey",
            "Allahabad pillar inscriptions",
            "Saumilla",
            "Dautilya",
            "Kumari Bibah",
            "Rangoon Pass",
            "Cachar",
            "Raghu Rai",
            "Jadavendra Adhyapaka",
            "at the start of a total solar eclipse",
            "In the Arctic circle",
            "the soil is porous",
            "intensity of an earthquake",
            "Bass Strait",
            "Potassium trichloride",
            "Monsoon region",
            "Knesset",
            "Vishakhapatnam",
            "Asom Sahitya Sanstha",
            "10.33 Hectares",
            "Guwahati",
            "Nagaon",
            "Hem Barua",
            "once a year",
            "Gazette",
            "The President of India according to his discretion",
            "12 years",
            "Everybody in India",
            "Production of persons before the court",
            "violating Human Rights",
            "Calcium phosphate",
            "A moderately regressive tax structure combined with flexible enforcement",
            "Tea",
            "Uranium-237",
            "Customs duties",
            "Marriage by registration",
            "It is translated in modern Assamese Language",
            "Karmakyoti",
            "Chandrakanta Singha",
            "Bipin Chandra Pal",
            "Kuladhar Chaliha",
            "New Delhi",
            "40 degree",
            "Rain water as it falls",
            "It is due to increase in humidity in air",
            "Hard disk",
            "Oxygen",
            "Pathology",
            "Nearest to the tank",
            "42%",
            "9,00,000",
            "6",
            "350",
            "150",
            "9000",
            "Seasons would have been shorter",
            "Malleus",
            "The President",
            "2005",
            "Ratan Tata",
            "Ramsay Mcdonald announced the communal award",
            "NH-7",
            "Ordinary Legislation and Money Bill",
            "52",
            "S. Radhakrishnan",
            "the water vapour of the air and retains its heat",
            "Indira Gandhi",
            "Contingency Fund of India",
            "The Himalayas",
            "Qatar",
            "Article 112",
            "World Disabled Day",
            "The share of industry increases",
            "Agro-based products",
            "Brave",
            "Hydrogen sulphide",
            "Guwahati",
            "English only",
            "Lord Mountbatten",
            "Jama Masjid",
            "Vikram Sarabhai was born",
            "Amnesty",
            "Abul Kalam Azad",
            "Lowering the blood pressure",
            "World Trade Organization",
            "Leaf",
            "Tropical hard wood forest",
            "Chaudhary Charan Singh",
            "It is a rigid stable block",
            "The Judges of the court are appointed according to the discretion of the Secretary General",
            "West Bengal",
            "1000 calories",
            "Gram Panchayat",
            "A.D.P. College, Nagaon",
            "Humayun",
            "London",
            "Brahmaputra, Ganges and Sutlej",
            "melanoma",
            "in the Vedic period",
            "Madhya Pradesh",
            "Mahanadi",
            "Jayadhwaj Singha",
            "Sir Henry S. Cotton",
            "British",
            "Moh Kheda",
            "Dikhow Chapari",
            "promote welfare of the backward section of the society",
            "263 km",
            "Afghanistan and Pakistan",
            "Jowar",
            "Westerly winds in the Southern Hemesphere",
            "Eastern Ghats",
            "Arabian Peninsula",
            "Tanpura",
            "Australia",
            "Greenwich Mean Time (GMT)",
            "311 km",
            "Methane",
            "Bhairabkunda",
            "pine trees",
            "Clayey",
            "1952",
            "gran pardon",
            "Article 352",
            "Chlorinated hydrocarbon",
            "Rangoon",
            "C. Rajagopalachari",
            "Prof. Abhijit Sen",
            "12",
            "Speaker of the Lok Sabha",
            "if President gives direction to do so",
            "Intervention of Prime Minister of India",
            "Samsung",
            "5 years",
            "Coal",
            "National Sample Survey",
            "being able of convert rupee notes into gold",
            "Defence Expenditure",
            "the price at which the govt. purchases the quantities of foodgrains for maintaining the public distribution system",
            "Jatindra Nath Mukherjee",
            "Sanyasi Rebellion",
            "Cape Comorin",
            "Muhammad Ali Jinnah",
            "Rajagopalachari and Liaqat Ali Report",
            "of mob violence at Chauri-Chaura",
            "Baba Ramananda",
            "Dadabhai Naoraji",
            "Mahatma Gandhi",
            "Dr. Bhupen Hazarika",
            "West Bengal",
            "1990",
            "Cuttak",
            "Jagannath Barooah",
            "Agomoni",
            "Thyroid",
            "15 cm",
            "increase the acidity of the soil",
            "acetic acid",
            "Bhatnagar Award",
            "Louis Pasteur",
            "Crop rotation",
            "Enhancement of soil quality",
            "3.4 km",
            "2,700",
            "6",
            "GQFDENN",
            "2 years",
            "A",
            "Reels",
            "700",
            "Vallabhbhai Patel",
            "Repo Rate",
            "July 5",
            "New Delhi",
            "Sikkim",
            "Sikkim",
            "Manila",
            "It is the 90 degree East-longitude",
            "Latitude",
            "Bigha",
            "high melting point",
            "Cool air",
            "Stockholm",
            "December 23",
            "A black spot on the sun",
            "Sodium bicarbonate",
            "Storme wave",
            "Barpeta",
            "Venenzuela",
            "Baahubali 2",
            "Manushi Chhillar",
            "Sugarcane",
            "August 1947",
            "US",
            "Nov-Dec",
            "Chile",
            "Sitanshu Yashaschandra",
            "Kandarpeswar Singha",
            "A",
            "Asterix",
            "Parbati Kumar Goswami",
            "In Sind in 1925",
            "Garba",
            "Pakistan",
            "3716.6 km",
            "Pasay",
            "Tomb of Dilvas Bano Begum, built by Aurangzeb at Aurangabad",
            "Bal Gangadhar Tilak",
            "Lord Cornwallis",
            "Sujata",
            "Soham Singh Bhankna",
            "Madras session in 1927",
            "Willium Wedderburn",
            "T. R. Phookan",
            "Liladhar Barua",
            "Siva Temple",
            "1935",
            "Fossils",
            "Apsara",
            "Earth",
            "Itatinga (Brazil)",
            "Lhotsa",
            "the Andaman and Nicobar Island",
            "Second",
            "Taupo Volcaono",
            "Cholera",
            "Bangalore",
            "TISCO, Jamshedpur",
            "Karnataka",
            "USA",
            "Guwahati",
            "Gyalaperi",
            "Motilal Nehru",
            "Buddha",
            "H5N1",
            "only by the relatives of the aggrieved person",
            "only after receiving instructions from the President",
            "The Chief Justice of the Supreme Court",
            "Iltutmish",
            "B. R. Ambedkar",
            "elected members of both houses of Parliament only",
            "71st Amendment Act",
            "Ten",
            "Bihar",
            "January to May",
            "Birju Munda",
            "72",
            "agrarian uprisings",
            "a separate Prime Minister",
            "On that day in 1949, India adopted its Constitution",
            "Medicine",
            "Boxer",
            "September 5",
            "Brain cells",
            "Tokyo",
            "British Parliament",
            "June 29",
            "Dutt Committee",
            "a major port in India",
            "Bimajyoti",
            "Dimapur",
            "Kaliabor",
            "Kuranganayani",
            "Physics",
            "Har Dayal",
            "1880",
            "it was highly localised",
            "Provincial Congress Organisation",
            "interference",
            "Harrowing Destiny",
            "troposphere, stratosphere, ionosphere",
            "6th to 11th day of the menstrual cycle",
            "sugar",
            "Chloride",
            "acids and iron",
            "SUKD",
            "150",
            "One year",
            "for a fixed term of five years",
            "Advisory jurisdiction of the Supreme Court",
            "the Chief Justice of the High Court",
            "a sphere is the most symmetrical object",
            "Hormone",
            "reflection of the blue light by the impurities of the sea water",
            "Atropine",
            "A.D. 78",
            "Holy Law of Islam",
            "City of the West",
            "Malladev",
            "Mir Lul-Jullah Shivazi",
            "Lord Lytton",
            "Comrade",
            "Lala Lajpat Rai",
            "Srinagar and Shimla",
            "Punjabi Litterateur",
            "Tsunami",
            "Zeenat Mahal",
            "Lahore",
            "El Nina",
            "Diana Hayden",
            "Hyderabad",
            "6820 km",
            "27",
            "1871",
            "Padma Vibhushan",
            "The burried the dead",
            "Hurricanes",
            "Ashoka",
            "Sabarmati",
            "Dibrugarh, Nalbari and Dhubri",
            "23rd April 2017",
            "Ministry of Tourism, Assam",
            "Nitin Gadkari",
            "Dhrub Batra",
            "32nd Amendment",
            "Rudra Singha",
            "Cosmic Rays",
            "Sumerians",
            "Autonomus public body",
            "The Lok Sabha",
            "Santosh Yadav",
            "W. Churchill",
            "Joseph Lister",
            "Pamni",
            "Languages",
            "Dhrupad",
            "Conception Moksha",
            "Bodo",
            "B. R. Ambedkar",
            "INS Vikrant",
            "Uber Cup - Badminton",
            "Theosophical Society",
            "Md. Ali Jinnah",
            "Cambodia",
            "Assam",
            "Akbar and Hemu",
            "Sikkim",
            "New York",
            "Garibi Hatao",
            "Bangladesh",
            "Article 152",
            "Bihar",
            "Ganga",
            "Coffee",
            "Akbar",
            "Calories",
            "Sunil Gavaskar",
            "Rigveda",
            "First",
            "1853",
            "Visakhapatnam",
            "4,3,1,2",
            "Ramayana",
            "Garden Moore",
            "Rajiv Gandhi",
            "Cricket",
            "Lumbini",
            "Nepal",
            "Delhi",
            "Vikram Seth",
            "Double Deflation",
            "World's Hygenic Day",
            "Shobha Dey",
            "Narsimham Committee",
            "Taxila",
            "Dr. B. R. Ambedkar",
            "Beas",
            "Kathakali",
            "R. N. Tagore",
            "Swaraj",
            "Papayas",
            "The Prime Minister",
            "France",
            "Spain",
            "Bihar",
            "Egypt",
            "Prevention of Money Laundering",
            "NABARD",
            "Dr. Jim Yong Kim",
            "8th September",
            "Arujana Award",
            "Samudragupta",
            "Venvadan National Park",
            "Ernakulam",
            "Delhi and Islamabad",
            "Shame",
            "12",
            "Drafting Committee",
            "Engineers Day",
            "Rukmini Haran",
            "12-19",
            "Prahlada Charitra",
            "Marco Polo",
            "Saltwater crocodile",
            "1917",
            "Saraswati Samman",
            "Iran",
            "Dr. A.P.J. Abdul Kalam",
            "Seventh",
            "Pralamba",
            "Australia",
            "Denmark",
            "Advocate General",
            "Gopala",
            "Ghajini",
            "Government of India",
            "National Development Council",
            "Ratan Tata",
            "Israel",
            "Meenakshi Temple"
    };
    public String SecondOption[] = {
            "Late Dr. Mamoni Raisom Goswami",
            "Amjad Ali",
            "Anupama Bhattacharya",
            "5th Royal Gurkha Rifles",
            "1.54%",
            "Agriculture",
            "24%",
            "Ms. Demi-Leigh Nel-Peters",
            "Dronacharya Award",
            "Classical Music",
            "NH-52",
            "88 years",
            "Green revolution",
            "Imprisonment without trial and summary procedure",
            "Humayun",
            "1898",
            "Fahien",
            "A synthetic egg",
            "Civil Disobedience Movement",
            "Jawaharlal Nehru",
            "October 3",
            "US",
            "Shiksha Darshan",
            "Siliguri",
            "Physics",
            "US",
            "Electrcardiograph",
            "South Korea",
            "Montagu-Chelmsford Act, 1919",
            "The Romans",
            "Lesser Himalayas",
            "Lion-tailed macaque of Western Ghats",
            "Aihole inscriptions",
            "Sudraka",
            "Silabhadra",
            "Apsara Sabah",
            "Khyber Pass",
            "Dhubri",
            "Purandar Singha",
            "Dhanesvara Adhyapaka",
            "at the end of  a total solar eclipse",
            "At 45 degree North latitude",
            "the level of underground water is high",
            "sweetness of a chemical",
            "Davis Strait",
            "Nitroglycerine",
            "Equatorial region",
            "Diet",
            "Paradip",
            "Assam Literary Society",
            "0.13387 Hectares",
            "Tezpur",
            "Darrang",
            "Dr. Banikanta Kakoti",
            "twice a year",
            "Report of the Public Accounts Committee",
            "The Prime Minister of India",
            "14 years",
            "Indian Citizens everywhere",
            "Releasing a person under arrest on bail",
            "producing Nucelar Bombs",
            "Calcium sulphate",
            "A moderately regressive tax structure combined with strong enforcement",
            "Coffee",
            "Cobalt-60",
            "Estate duty",
            "Marriage by consent",
            "It modified the main story of the epic",
            "Gyanjyoti",
            "Kamaleswar Singha",
            "Aurobindo Ghosh",
            "Tayyebulla",
            "Mumbai",
            "270 degree",
            "Sea water",
            "It is due to the rise in atmospheric pressure",
            "Hardware",
            "Nitrogen",
            "Nidology",
            "Farther for the tank",
            "60%",
            "9,00,000",
            "3",
            "375",
            "350",
            "9001",
            "Seasons would have been longer",
            "Femur",
            "The Defense Minister",
            "2006",
            "Bimal Jalan",
            "Congress and Muslim League had difference in opinions",
            "NH-1",
            "Ordinary Legislation only",
            "54",
            "Rajendra Prasad",
            "the infrared part of the solar radiation",
            "Rajiv Gandhi",
            "Public Account Fund",
            "The Eastern Ghats",
            "Oman",
            "Article 74",
            "National Safety Day",
            "The number of persons employed in agriculture declines",
            "Fast-moving consumer goods (FMCG)",
            "Life of Pi",
            "Oxygen",
            "Tezpur",
            "Hindi only",
            "Sir Cyril Redcliffe",
            "Qutub Minar",
            "C.V. Raman Discovered Raman Effect",
            "Armistice",
            "Khan Abdul Ghaffar Khan",
            "Lowering the blood sugar",
            "European Economic Community",
            "Root",
            "Equatorial rain forest",
            "Gulzarilal Nanda",
            "It is a rigid unstable block",
            "No two judges may belong to the same country",
            "Arunachal Pradesh",
            "1800 calories",
            "Owner of a Factory",
            "M.C. College, Barpeta",
            "Shahjahan",
            "New York",
            "Brahmaputra, Sutlej and Yamuna",
            "silicosis",
            "around 600 BC",
            "Andhra Pradesh",
            "Ram Ganga",
            "Pratap Singha",
            "Mr. F. W. Sudmersen",
            "Arabians",
            "Moho-Ho",
            "Saraguri Chapari",
            "lay down positive instructions which would guide state policy at all levels",
            "260 km",
            "China and Pakistan",
            "Barley",
            "Westerly winds in the Northern Hemesphere",
            "Western Ghats",
            "Indian Peninsula",
            "Sitar",
            "Thailand",
            "International Standard Time (IST)",
            "211 km",
            "Nitrous oxide",
            "Umananda",
            "sunflower",
            "Sandy",
            "1956",
            "remove the judges of Supreme Court",
            "Article 356",
            "Fluorinated hydrocarbon",
            "Singapore",
            "Acharya J. B. Kripalani",
            "Dr. Montek Singha Ahluwalia",
            "14",
            "Chief Justice of Supreme Court",
            "if Supreme Court directs it to make such a law",
            "Supreme Court Judgement",
            "Nokia",
            "7 years",
            "Nuclear Fuels",
            "Planning Commission",
            "allowing the value of rupee to be fixed by market forces",
            "Expenditure on public utility services",
            "the declared prices at which the govt. purchases the surplus foodgrains from the farmers in case of a glut in the market",
            "Madan Lal Dhingra",
            "Santal Rebellion",
            "Point Palmyras",
            "Badruddin Tyabji",
            "Wavell Plan",
            "of Gandhi-Irwin Pact",
            "Baba Ram Singh",
            "Swami Dayanand",
            "Jawaharlal Nehru",
            "Nirmalprava Bordoloi",
            "Tripura",
            "1991",
            "Kharavela",
            "Raja Naranarayan Singha",
            "Baxirhat",
            "Pituitary",
            "25 cm",
            "restore nitrates to the soil",
            "citric acid",
            "Kalinga Prize",
            "Carolus Linneus",
            "Crop differentiation",
            "Replenishment of forests",
            "3.8 km",
            "3,100",
            "4",
            "GFDNEQN",
            "3 years",
            "C",
            "Recordings",
            "500",
            "Madan Mohan Malviya",
            "Bank Rate",
            "January 25",
            "Kilkata",
            "Arunachal Pradesh",
            "Goa",
            "Singapore",
            "It is the equator",
            "Altitue",
            "Katha",
            "low melting point",
            "Warm air",
            "Belgrade",
            "October 21",
            "A black spot on the moon",
            "Sodium hydroxide",
            "Tsunami",
            "Bihpuria",
            "Equador",
            "Toilet: Ek Prem Katha ",
            "Anukreethy Vas",
            "Bajra",
            "June 1948",
            "Chile",
            "Jan-Feb",
            "France",
            "Mahabaleshwar Sail",
            "Rudra Singha",
            "B12",
            "Dennis",
            "Holiram Deka",
            "In Lahore in 1941",
            "Nautanki",
            "Azerbaijan",
            "4716.6 km",
            "Singapore",
            "Akbar's Tomb at Sikandra",
            "Bhagat Singh",
            "Lord Wellesely",
            "Mahamaya",
            "Bhagwan Singh",
            "Bombay session in 1926",
            "Lord Ripon",
            "Srinivas Ayengar",
            "Nabin Chandra Bordoloi",
            "Kali Temple",
            "1925",
            "Trees",
            "Siva",
            "Jupitar",
            "Angel (Venenzuela)",
            "Makalu",
            "Dadra and Nagar Haveli",
            "First",
            "Mauna Loa Volcano",
            "Typhoid",
            "Udaipur",
            "VSL, Bhadravati",
            "Tamil Nadu",
            "Britain",
            "Silchar",
            "Gyantse",
            "Mohammad Ali Jinnah",
            "Vishnu",
            "HIV",
            "by the member of any voluntary society",
            "only after receiving instructions from the Prime Minister",
            "The Chief Justice of the Respective High Court",
            "Akbar",
            "M. N. Roy",
            "elected members of the legislative assemblies of the states only",
            "69th Amendment Act",
            "Seventeen",
            "Chattisgarh",
            "June to September",
            "Birsa Munda",
            "436",
            "tribal clashes",
            "a separate Constitution of its own",
            "On that day in 1885, the Indian National Congress came into existence",
            "Fiction writing",
            "Sprinter",
            "August 5",
            "Liver",
            "Singapore",
            "Constituent Assembly",
            "April 1",
            "Chakravarty Committee",
            "the name of a commet recently discovered",
            "Jibonjyoti",
            "Shillong",
            "Tezpur",
            "Princess Jaimoti",
            "Medicine",
            "Bhagat Singh",
            "1890",
            "it was against freedom",
            "Assam Congress Association",
            "reflection",
            "Carnival Destiny",
            "ionosphere, stratosphere, troposphere",
            "15th to 19th day of the menstrual cycle",
            "calcium chloride",
            "Bromide",
            "hydrocarbons and liquids",
            "SDKU",
            "100",
            "Six months",
            "as long as he/she enjoys the confidence of Lok Sabha",
            "Applellate jurisdiction of the Supreme Court",
            "the Governor of the state",
            "the viscosity does not allow it to spread out",
            "Insulin",
            "reflection of blue sky by the sea water and scattering of blue light by water molecules",
            "Cinochonine",
            "A.D. 70",
            "Holy book of Islam",
            "City of the Dead",
            "Sukladhwaj",
            "Mir Jumla",
            "Lord Ripon",
            "Abhinava Bharat",
            "Bhagat Singh",
            "Dehradun and Shimla",
            "Marathi Litterateur",
            "Tornado",
            "Fatima Begum",
            "Kathua",
            "La Nina",
            "Lara Dutta",
            "Bengalore",
            "4820 km",
            "28",
            "1881",
            "Padma Shri",
            "The cremated the dead and burried the remains",
            "Tornadoes",
            "Bimbisara",
            "Sidhpur",
            "Silchar, Jorhat and Guwahati",
            "23rd September 2017",
            "Centre for Agriculture and Rural Development (CARD), a New Delhi-based NGO",
            "Sarbananda Sonowal",
            "Abhinav Bindra",
            "42nd Amendment",
            "Pratap Singha",
            "Dynamite",
            "Chinese",
            "Constitutional body",
            "The Rajya Sabha",
            "Bachendri Pal",
            "Anthoney Eden",
            "Edward Jenner",
            "Manu",
            "Pictures or images",
            "Ghazal",
            "Caste system",
            "Santhtal",
            "K. M. Munshi",
            "INS Victory",
            "Rovers Cup - Football",
            "Parthana Samaj",
            "Jawaharlal Nehru",
            "Laos",
            "West Bengal",
            "Rajputs and Mughals",
            "Meghalaya",
            "Geneva",
            "Dilli Chalo",
            "Bhutan",
            "Article 352",
            "Gujarat",
            "Brahmaputra",
            "Tea",
            "Shah Jahan",
            "Kilograms",
            "Dhayn Chand",
            "Samveda",
            "Second",
            "1900",
            "kandla",
            "2,4,3,1",
            "Mahabharata",
            "Charles Babbage",
            "John Lennon",
            "Hockey",
            "Sanchi",
            "India",
            "Arunachal Pradesh",
            "Khushwant Singh",
            "Deflation",
            "World Red Cross Day",
            "Javed Akhtar",
            "Hilton-Yong Commission",
            "Multan",
            "Netaji Subhash Chandra Bose",
            "Ravi",
            "Kathak",
            "Bankim Ch Chatarjee",
            "Swadeshi",
            "Cholas",
            "The Election Commission",
            "UNO",
            "Portugal",
            "Uttar Pradesh",
            "Syria",
            "Control of Foreign Direct Investment",
            "SIDBI",
            "Goran Hadzic",
            "8th March",
            "Kalidas Samman",
            "Bhutivarman",
            "Periyar National Park",
            "Kozhikode",
            "Kandla and Dhaka",
            "Freedom at Midnight",
            "13",
            "Constituent Committee",
            "Youth Day",
            "Kitabat Manjari",
            "19-21",
            "Hastir Vidyanarva",
            "Vasco da Gama",
            "Olive ridley turtle",
            "1944",
            "Vyas Samman",
            "Sri Lanka",
            "Dr. Vikram Sarabhai",
            "Eighth",
            "Harsadeva",
            "Canada",
            "Finland",
            "Attorney General",
            "Brahmapala",
            "Rock Star",
            "World Trade Organization (WTO)",
            "Union Budget",
            "Bobhti Jindal",
            "Canada",
            "Yadagirigutta Temple"
    };
    public String ThirdOption[] = {
            "Dr. Dhrubajyoti Bora",
            "Amol Parekar",
            "Pratime Pandey Baruah",
            "Madras Light Cavalry",
            "1.97%",
            "Social service",
            "34%",
            "Ms. Irene Esser",
            "Kalinga Award",
            "Yoga",
            "NH-31",
            "78 years",
            "White revolution",
            "Suppression of Khilafat Movement",
            "Sikandar Lodi",
            "1798",
            "Hiuen Tsang",
            "A quality guarantee stamp for commodities like eggs, ghee, honey etc.",
            "Swadeshi Movement",
            "Motilal Nehru",
            "November 3",
            "China",
            "Vigyan Darshan",
            "Jalpaiguri",
            "Chemistry",
            "England",
            "Electrocardiograde",
            "Pakistan",
            "Govt. of India Act, 1935",
            "The Chinese",
            "Great Himalayan Range",
            "Slow loris of Assam",
            "Ajanta Caves",
            "Shaunaka",
            "Charaka",
            "Devi Nritya",
            "Pangsau",
            "Nagaon",
            "Bhaskaravarmana",
            "Rajendra Adhyapaka",
            "only at the perepheral regions of the totality trail",
            "In the Tropic of Cancer",
            "there are perennial rivers",
            "purity of milk",
            "Hudson Strait",
            "Mercuric oxide",
            "Savanna region",
            "Storting",
            "Marmugao",
            "Assam Sahitya Sanmilani",
            "13.387 Hectares",
            "Silchar",
            "Dhemaji",
            "Anandaram Barua",
            "thrice a year",
            "White Paper",
            "The President of India on the advice of the Prime Minister",
            "18 years",
            "All legal entities",
            "Quashing the order of the administrative authority",
            "involved in Drug Smuggling",
            "Calcium silicate",
            "A moderately prograssive tax structure combined with strong enforcement",
            "Coconut",
            "Iodine-131",
            "Excise duty",
            "Marriage by capture",
            "It is the first regional translation of the epic",
            "Dharmajyoti",
            "Jogeswar Singha",
            "Lokmanya Tilak",
            "Kanaklal Barua",
            "Bangalore",
            "-40 degree",
            "Water from hotspring",
            "It is due to the fall in atmospheric pressure",
            "Software",
            "Carbon dioxide",
            "Neurology",
            "Near the middle of the building",
            "52%",
            "7,00,000",
            "2",
            "400",
            "250",
            "901",
            "There would have been no changes of seasons",
            "Incus",
            "The Prime Minister",
            "2004",
            "Rahul Bajaj",
            "Round Table conference failed to satisfy Indian political aspirations",
            "NH-2",
            "Ordinary Legislation  and Constitution Amendment Bill",
            "56",
            "C. Rajagopalachari",
            "all the solar radiation",
            "Nargis Dutt",
            "Consolidated Account Fund",
            "The Western Ghats",
            "Kuwait",
            "Article 268",
            "World Consumer Rights Day",
            "Labour-intensive industries increases",
            "The core and infrastructure sector",
            "Argo",
            "Carbon dioxide",
            "Jorhat",
            "English, Hindi or Mother Tongue",
            "Sir Stafford Cripps",
            "Red Fort",
            "First Indian spacecraft was launched",
            "Military Pact",
            "Muhammad Ali Jinnah",
            "Protecting the lungs from cancer",
            "International Monetary Fund",
            "Bark",
            "Deciduous mixed forest",
            "Chandrashekhar",
            "It has thick layer of heavy lava",
            "The court consists of 20 judges",
            "Assam",
            "1900 calories",
            "The Press",
            "B.N. College, Dhubri",
            "Akbar",
            "Los Angeles",
            "Brahmaputra, Indus and Sutlej",
            "goitre",
            "in Maurya period",
            "Maharashtra",
            "Yamuna",
            "Jayaditya Singha",
            "Manik Chandra Barua",
            "Portuguese",
            "Moho-Bhago",
            "Beltola Chapari",
            "implement Gandhiji's idea for decentralised state",
            "125 km",
            "China and India",
            "Bajra",
            "One of the major water currents of the Atlantic ocean",
            "Shivaliks",
            "Malay Peninsula",
            "Santoor",
            "India",
            "Greenwich Standard Time (GST)",
            "111 km",
            "Hydrogen",
            "Kamakhya Temple",
            "tea",
            "Clayey loams and deltas",
            "1962",
            "declare emergency",
            "Article 21",
            "Clorofluoro hydrocarbon",
            "Tokyo",
            "Mahatma Gandhi",
            "Dr. Subeer Gokaran",
            "16",
            "Vice-Chairman of Rajya Sabha",
            "if Rajya Sabha supports with two-thrid majority",
            "A joint session of the two Houses of the Parliament",
            "Motorola",
            "10 years",
            "Petroleum, L.P.G, Diesel, Bio-gas",
            "National Productivity Council",
            "freely permitting the conversion of rupees to other major currencies and vice versa",
            "Central Govt's interest payments",
            "the necessary price compensation provided by the govt. to the farmers in case of crop damage due to natural calamities",
            "Vinayak Damodar Savarkar",
            "Indigo Disturbances",
            "Indira Point",
            "Sir Syed Ahmed Khan",
            "INA trials",
            "The Government accepted the demands in toto",
            "Ramchandra",
            "Swami Vivekanand",
            "Sardar Patel",
            "Purushottam Das",
            "Andhra Pradesh",
            "1992",
            "Kalinga",
            "Lakshminath Bezbaruah",
            "Dhubri",
            "Pancreas",
            "30 cm",
            "increase the alkalinity of the soil",
            "lactic acid",
            "UN Award for Size",
            "Hippocrates",
            "Crop rearrangement",
            "Drive against pollution of soil",
            "4.4 km",
            "2,900",
            "3",
            "GREDENM",
            "1 years",
            "B",
            "Files",
            "400",
            "Asaf Ali",
            "Cash Reverse Ratio",
            "November 2",
            "Surat",
            "Meghalay",
            "Tripura",
            "London",
            "It is the 180 degree longitude",
            "Distance from sea",
            "Acre",
            "high resistance",
            "Cold water",
            "Venice",
            "September 18",
            "A dead star with an immense forces of gravitational attraction",
            "Magnesium sulphate",
            "Tidal wave",
            "Nagaon",
            "Bolivia",
            "Village Rockstars",
            "Shreya Rao Kamavarapu",
            "Mustard",
            "Agust 1949",
            "Russia",
            "Sept-Oct",
            "Argentina",
            "Padma Sachdev",
            "Lakshmi Singha",
            "B11",
            "Donald Duck",
            "M.C. Pathak",
            "In Calcutta in 1931",
            "Thoda",
            "Iran",
            "5716.6 km",
            "New Delhi",
            "Rang Mahal",
            "Vallabh Bhai Patel",
            "Lord Minto",
            "Yashodhara",
            "Ram Chandra",
            "Calcutta session in 1927",
            "Sister Nivedita",
            "Gopinath Bordoloi",
            "Tarunram Phookan",
            "Laxmi Temple",
            "1915",
            "Stars",
            "Urvashi",
            "Mars",
            "Roraima (Guyana)",
            "Cho Oyu",
            "Lakshadweep",
            "Third",
            "Beeven Berg Volcano",
            "Jaundice",
            "Bombay",
            "HSL, Durgapur",
            "Andhra Pradesh",
            "Japan",
            "Dibrugarh",
            "Digatse",
            "Arun Asaf Ali",
            "Nataraj",
            "H6N2",
            "by a Govt. pleader",
            "only after receiving instructions from the Chiefe Justice of the Supreme Court",
            "The President of India",
            "Humayun",
            "Jawaharlal Nehru",
            "elected members of both houses of both the Parliament and the legislative assemblies of the states",
            "73rd Amendment Act",
            "Twenty",
            "Gujarat",
            "July to December",
            "Bhikhu Munda",
            "1036",
            "lingusitic clashes",
            "a separate defence forces of its own",
            "On that day in 1930, the Congress observed Independence day in the country",
            "Reporting",
            "Weight Lifter",
            "July 5",
            "Kidney",
            "Manila",
            "Governor General",
            "March 28",
            "Mahalanobis Committee",
            "a sort of weapon",
            "Gyanjyoti",
            "Guwahati",
            "Sibsagar",
            "Ramani Gabharu",
            "Chemistry",
            "Sohan Singh Bhakra",
            "1901",
            "it denied membership to the non-Muslims",
            "Radical Assamese Association",
            "reflection and refraction",
            "Sea Harriers",
            "stratosphere, troposphere, ionosphere",
            "on the 14th day of the menstrual cycle",
            "sodium chloride",
            "Fluoride",
            "acids, hydrocarbons and liquids",
            "UKDS",
            "125",
            "Three months",
            "for a fixed term of six years",
            "Original jurisdiction of the Supreme Court",
            "the President of India",
            "it has minimum surface energy",
            "Glycogen",
            "absorption of other colors by the water molecules",
            "Ephedrine",
            "A.D. 72",
            "Holy place of Islam",
            "City of the Dawn",
            "Gohain Kamal",
            "Sultan Ghiyasuddin Aulia",
            "Lord Curzon",
            "Al-Hilal",
            "Subhash Chandra Bose",
            "Gangtok and Tibet",
            "Hindi Litterateur",
            "Cyclone",
            "Hazrat Mahal",
            "Chagai Hills",
            "La Cool",
            "Priyanka Chopra",
            "Lucknow",
            "7820 km",
            "29",
            "1891",
            "Padma Bhushan",
            "The dead were left for the wild animals",
            "Cyclones",
            "Chandragupta Maurya",
            "Idar",
            "Tezpur, Tinsukia, Dhubri",
            "23rd April 2018",
            "Ministry of Commerce and Industry, Assam",
            "Narendra Modi",
            "Harjinder Singh",
            "15th Amendment",
            "Gadadhar Singha",
            "Dynamo",
            "Egyptians",
            "Extra constitutional body",
            "Both the Houses",
            "Anna Chandi",
            "Clement Attlee",
            "Henry William",
            "Kautilya",
            "Human beauty",
            "Thumri",
            "Conception of soul",
            "Gond",
            "Jawaharlal Nehru",
            "INS Hamla",
            "Irani Trophy - Hockey",
            "Brahmo Samaj",
            "Mrs. Indira Gandhi",
            "China",
            "Punjab",
            "Babar and Ibrahim Lodi",
            "Manipur",
            "Madrid",
            "Jai Jawan, Jai Kisan",
            "Nepal",
            "Article 382",
            "Maharashtra",
            "Cauvery",
            "Mica",
            "Jahangir",
            "Meters",
            "Sachin Tendulkar",
            "Yajurveda",
            "Third",
            "1904",
            "Mumbai",
            "4,2,3,1",
            "Ramcharit Manas",
            "Tim Berners-Lee",
            "Barack Obama",
            "Football",
            "Sarnath",
            "Indonesia",
            "Gujarat",
            "Anita Desai",
            "Double Dip Recession",
            "World Health Day",
            "Anupam Kher",
            "Fazil Ali Commission",
            "Peshwar",
            "Vallabhbhai Patel",
            "Padmia",
            "Bharatnatyam",
            "Muhammad Iqbal",
            "Quit India",
            "Pallavas",
            "The Lok Sabha",
            "UNESCO",
            "Italy",
            "Jharkhand",
            "Turkey",
            "Nuclear Energy",
            "IDBI Bank",
            "Robert B. Zoellick",
            "28th March",
            "Dada Saheb Phalke Award",
            "Pushyavarman",
            "Bandipur National Park",
            "Thiruvananthapuram",
            "Howrah and Dhaka",
            "Satanic Verses",
            "11",
            "Union Constitution Committee",
            "Hindi Divas",
            "Kumara Harana",
            "25-28",
            "Kumara Harana",
            "Genghis Khan",
            "Gangetic dolphin",
            "1963",
            "Kalidas Samman",
            "Bhutan",
            "Dr. Tessy Thomas",
            "Ninth",
            "Salastamba",
            "Argentina",
            "Iceland",
            "Solicitor General",
            "Ratnapala",
            "Slumdog Millionaire",
            "Asian Development Bank (ADB)",
            "Planning Commission",
            "Lakshmi Mittal",
            "Sweden",
            "Surya Temple"
    };
    public String FourthOption[] = {
            "Dr. Malini",
            "Adoor Gopalakrishnan",
            "Aideu Handique",
            "None of the above",
            "2.64%",
            "Irrigation and flood control",
            "None of the above",
            "Ms. Olivia Culpo",
            "Dhyan Chand Award",
            "Acting",
            "NH-37",
            "108 years",
            "Yellow revolution",
            "Imposition of restrictions on freedom of the press",
            "Ibrahim Lodi",
            "1918",
            "Megasthenes",
            "A medicine for AIDS",
            "Non-Cooperation Movement",
            "Mahatma Gandhi",
            "December 3",
            "India",
            "None of the above",
            "New Bongaigaon",
            "Mathematics",
            "Germanye",
            "Electrocardiography",
            "Japan",
            "India Independence Act, 1947",
            "The Arabs",
            "Dhauladhar Range",
            "Hoolock gibbon of Assam",
            "Alapadu grant",
            "Susrutha",
            "Visaakhadatta",
            "Bowari Bibah",
            "Fangsu Pass",
            "Karbi-Anglong",
            "Durlabhanarayana",
            "Mukunda Adhyapaka",
            "only at the central region of the totality trail",
            "At the equator",
            "region is densely populated",
            "acidity or alkalinity of solution",
            "Bering Strait",
            "Graphite",
            "Temperate region",
            "House of the people",
            "Haldia",
            "Asomiya Sahitya Sanmilani",
            "133.87 Hectares",
            "Jorhat",
            "Dhubri",
            "Maheshwar Neog",
            "four times a year",
            "Blue Document",
            "The Parliament",
            "20 years",
            "All adult humans in India",
            "An order to enforce freedom of expression",
            "supporting Cross-Border terrorism",
            "Calcium oxide",
            "A moderately complex tax structure combined with flexible enforcement",
            "Spices",
            "Uranium-235",
            "Sales tax",
            "Marriage by love",
            "None of the above",
            "Jibonjyoti",
            "Purandar Singha",
            "Bhikaji Cama",
            "Tarun Ram Phookan",
            "Nagpur",
            "248 degree",
            "Deep well water",
            "It is due to the severe heat energy from the sun",
            "Disk drive",
            "Nitrous oxide",
            "Genetics",
            "Next to the top floor",
            "44%",
            "6,00,000",
            "7",
            "200",
            "100",
            "90",
            "None of the above",
            "Stapes",
            "The Parliament",
            "2000",
            "Naresh Chandra",
            "None of the above",
            "NH-3",
            "Constitution Amendment Bill only",
            "58",
            "Sardar Patel",
            "the ultra-violet part of the solar radiation",
            "Prem Nath",
            "Deposit and Advances Fund",
            "The Indo-Gangetic Plains",
            "Bahrain",
            "Article 371",
            "Commonwealth Day",
            "The share of agriculture in the national product declines",
            "Software industry",
            "Les Miserables",
            "Nitrogen",
            "Silcharn",
            "English or Hindi",
            "Sir Pethwick Lawrence",
            "Humayun Tomb",
            "The first science policy was drafted",
            "Accord",
            "Hazlul Haque",
            "Increasing memory power",
            "United Nations Organization",
            "Bean",
            "Coniferous forests",
            "V.P. Singh",
            "It has old crystalline  igneous rocks",
            "The statue of the International Court of Justice is not an integral part of the UN Charter",
            "Meghalaya",
            "2200 calories",
            "The council of ministers",
            "J.B. College, Jorhat",
            "Sher Shah Suri",
            "Tokyo",
            "Chenab, Ravi and Sutlej",
            "kidney stone",
            "with the beginning of agriculture and trade",
            "Mizoram",
            "Godavari",
            "Pramatta Singha",
            "Sir Stuart Bailey",
            "French",
            "Moh Puja",
            "Ajan Chapori",
            "check the arbitrary powers by the government",
            "160 km",
            "Afghanistan and Iran",
            "Ragi",
            "Group of wild horses",
            "Vindhyas",
            "None of the above",
            "Veena",
            "China",
            "Universal Co-ordinated Time (UCT)",
            "101 km",
            "Carbon dioxide",
            "Negheriting",
            "mustard",
            "Rice regur",
            "1964",
            "issue ordinances",
            "Article 26",
            "Bromohydrocarbon",
            "Jakarta",
            "Maya Prakash Narian",
            "Dr. Y. V. Reddy",
            "18",
            "Seniormost Governor",
            "if Lok Sabha supports with two-thrid majority",
            "Parliamentary Committee appointed by the President of India",
            "LG",
            "15 years",
            "Hydro electricity",
            "Central Statistical Orgaization",
            "developing an international market for currencies in India",
            "Expenditure on subsidies",
            "the prices at which the govt. supplies foodgrains through fair price shops",
            "Lala Hardayal",
            "Pabna Disturbances",
            "Point Calemere",
            "Abdul Kalam Azad",
            "Elections",
            "The Khilafat issue fizzled out with abolition of the office of the Caliph in Turkey",
            "Baba Ramapyan",
            "Ramkrishna Paramhansa",
            "J.B. Kripalani",
            "Sankardeva",
            "Karnataka",
            "1994",
            "Magadh",
            "Upendranath Barua",
            "Jogighopa",
            "Adrenal",
            "50 cm",
            "make the soil more porous",
            "tartaric acid",
            "Vikram Saerabhai Award",
            "Theophrastus",
            "Crop cultivation",
            "Growing of fishes and aquatic animals",
            "4.8 km",
            "3,000",
            "2",
            "GRFDFNN",
            "Insufficient data to calculate",
            "D",
            "Floppy",
            "300",
            "B. R. Ambedkar",
            "Statutory Liquidity Ratio",
            "April 26",
            "Bhopal",
            "West Bengal",
            "Mizoram",
            "Lahore",
            "It is the 0 degree longitude",
            "Longitude",
            "Hectare",
            "low specific heat",
            "Steel",
            "Rome",
            "June 15",
            "A blank space in galaxy",
            "Copper sulphate",
            "P-wave",
            "Narayanpur",
            "Argentina",
            "Thondimuthalum Driksakshiyum",
            "Meenakshi Chaudhary ",
            "Cotton",
            "January 1950",
            "China",
            "June-July",
            "Ireland",
            "Veerappa Moily",
            "Joyaddhaj Singha",
            "D",
            "Mickey Mouse",
            "Anil Ratan Borthakur",
            "In Bombay in 1935",
            "Bhangra",
            "Samoa",
            "7516.6 km",
            "Kathmandu",
            "Dinpanah",
            "Chandra Sekhar Azad",
            "Lord Dalhousie",
            "Gotami",
            "Gurudin Singh",
            "Surat session in 1928",
            "Mrs. Annie Besant",
            "Lokmanya Tilak",
            "Kuladhar Chaliha",
            "Vishnu Temple",
            "1930",
            "Battery",
            "Parvati",
            "Saturn",
            "Pilao (Brazil)",
            "Chomolungma",
            "Goa",
            "Fifth",
            "Toba Volcano",
            "Fluorosis",
            "Hyderabad",
            "HSL, Bhilai",
            "Maharashtra",
            "Germany",
            "Shillong",
            "Sinyung La",
            "Bal Gangadhar Tilak",
            "Uma-Maheshwara",
            "PH3",
            "by any member of the public",
            "under no circumstances",
            "The Cabinet",
            "Jehangir",
            "Jyoti Basu",
            "all the members of Lok Sabha only",
            "81st Amendment Act",
            "Thirteen",
            "Maharashtra",
            "August to November",
            "Budhu Munda",
            "936",
            "communal clashes",
            "a separate currency system",
            "On that day in 1947, India became truly Sovereign",
            "Script writing",
            "Swimmer",
            "June 5",
            "Spinal Column",
            "Bangkok",
            "Parliament of India",
            "February 28",
            "Rangaranjan Committee",
            "a new game",
            "Dharmajoti",
            "Imphal",
            "Golaghat",
            "Ex-queen Kamaleswari Devi",
            "Economics",
            "Raj Guru",
            "1947",
            "it was subbotaged by its own leaders",
            "Assam Congress Party",
            "interference and reflection",
            "Ocean King",
            "troposphere, ionosphere, stratosphere",
            "any time in the menstrual cycle",
            "potassium chloride",
            "Sulphide",
            "iron, hydrocarbons and liquids",
            "USKD",
            "75",
            "Fourteen days",
            "as long as he/she enjoys the confidence of both Lok Sabha and Rajya Sabha",
            "None of the above",
            "the Chief Justice of India",
            "the strong gravitational field of the earth does not allow it to take any other shape",
            "Engyme",
            "none of the above",
            "Morphine",
            "A.D. 76",
            "Holy painting of Islam",
            "City of Joy",
            "Rudra Singha",
            "Alauddin Hussain Shah",
            "William Bentinck",
            "Krantikari Dal",
            "Ranjit Singh",
            "Srinagar and Leh",
            "Telugu Litterateur",
            "Earthquake",
            "Mumtaj Mahal",
            "Karachi",
            "El cool",
            "Diya Mirza",
            "Patna",
            "8820 km",
            "33",
            "1901",
            "Bharat Ratna",
            "All of the above",
            "Typhoons",
            "Harsha",
            "Asawal",
            "Tezpur, Jorhat, Bongaigaon",
            "23rd June 2018",
            "Indian Society of Agribusiness Professionals (ISAP), a New Delhi-based NGO",
            "Chandra Mohan Patowary",
            "Mary Kom",
            "None of the above",
            "Naranarayan",
            "Penicillin",
            "Mesopotaminas",
            "Part of a ministry",
            "The President of India",
            "Arunima Sinha",
            "Arthur Greenwood",
            "Ernest Rutherford",
            "Bhishma",
            "Human feelings",
            "Jhoomar",
            "Ignorance of the idea of God",
            "Jarawas",
            "Syed Mohammad Saadullah",
            "INS Khukri",
            "Ezra Cup - Polo",
            "Ram Krishna Mission",
            "Morarji Desai",
            "Phillipines",
            "Rajasthan",
            "None of these",
            "Arunachal Pradesh",
            "Paris",
            "Inquilab Zindabad",
            "All of these",
            "Article 370",
            "Madhya Pradesh",
            "Godavari",
            "Manganese",
            "Aurangzeb",
            "Yards",
            "Prakash Padukone",
            "Atharvaveda",
            "Fourth",
            "1864",
            "Chennai",
            "1,2,3,4",
            "Bhagavad Gita",
            "Steve Jobs",
            "Indira Gandhi",
            "Volleyball",
            "Bodh Gaya",
            "Cambodia",
            "Tamil Nadu",
            "Arundhati Roy",
            "None of these",
            "International Yoga Day",
            "Amitabh Bacchan",
            "Deshmukh Commission",
            "Kanchipuram",
            "Jawaharlal Nehru",
            "Ganga",
            "All of the above",
            "Lata Mangeshkar",
            "Non-Cooperation",
            "Marathas",
            "The Supreme Court",
            "ILO",
            "Greece",
            "Uttaranchal",
            "Libya",
            "Prevention of Human Rights Violation",
            "EXIM Bank",
            "Kristalina Georgeiva",
            "18th September",
            "Shanti Swarup Bhatnagar Award",
            "Mahabhutivarman",
            "Corbett National Park",
            "Kannur",
            "Attari and Amritsar",
            "The Audacity of Hope",
            "2",
            "Working Committee",
            "Sanskrit Divas",
            "Mahabharata",
            "21-18",
            "Ramayana",
            "Christopher Columbus",
            "Gharial",
            "In all these three years",
            "Tulsidas Samman",
            "Indonesia",
            "Dr. Homi J. Bhaba",
            "Tenth",
            "Vanamala",
            "India",
            "New Zealand",
            "Public Prosecutor",
            "Harshapala",
            "Fashion",
            "United Nations Conference on Trade and Development (UNCTAD)",
            "Prime Minister of India",
            "Mukesh Ambani",
            "Afghanistan",
            "Tirupati Balaji Temple"
    };
    public int CorrectAns[] = {
            2,  4,  3,  1,  1,  2,  2,  2,  3,  3,  4,  3,  4,  2,  2,  1,  1,  3,  1,  3,  4,  3,  1,  2,  4,  3,  1,  4,  2,  4,  2,  4,  2,  4,  2,  2,  3,  1,  4,  3,  3,  1,  3,  4,  4,  2,  2,  1,  3,  3,  2,  3,  2,  2,  2,  3,  3,  3,  2,  1,  2,  4,  3,  1,  2,  2,  3,  3,  3,  4,  3,  4,  3,  3,  4,  3,  2,  3,  3,  2,  3,  4,  4,  2,  1,  2,  3,  4,  1,  1,  1,  1,  1,  2,  4,  3,  2,  3,  3,  3,  3,  1,  3,  4,  4,  3,  1,  4,  3,  2,  3,  2,  2,  3,  1,  3,  4,  1,  1,  1,  2,  2,  2,  3,  4,  3,  1,  3,  2,  4,  3,  4,  1,  2,  3,  2,  2,  2,  1,  3,  2,  1,  2,  1,  4,  3,  4,  3,  3,  3,  3,  3,  2,  1,  1,  2,  1,  3,  4,  2,  2,  3,  3,  1,  3,  1,  4,  3,  2,  2,  3,  3,  3,  2,  3,  1,  2,  3,  4,  3,  3,  2,  3,  3,  2,  2,  2,  3,  1,  2,  3,  1,  2,  2,  1,  3,  1,  1,  3,  4,  4,  4,  1,  2,  4,  3,  2,  1,  3,  4,  3,  2,  4,  2,  1,  3,  1,  2,  4,  1,  3,  2,  2,  2,  2,  4,  3,  1,  1,  2,  2,  4,  1,  3,  2,  4,  2,  1,  2,  2,  4,  2,  1,  3,  2,  1,  4,  1,  1,  1,  2,  2,  4,  1,  2,  4,  4,  4,  2,  3,  1,  3,  4,  2,  4,  1,  2,  1,  3,  1,  2,  3,  4,  2,  4,  2,  2,  2,  1,  2,  3,  2,  3,  4,  4,  3,  2,  1,  3,  1,  2,  2,  1,  4,  3,  3,  1,  3,  1,  3,  2,  1,  2,  3,  2,  2,  2,  2,  2,  2,  3,  2,  3,  2,  2,  3,  1,  1,  2,  2,  3,  2,  2,  1,  4,  3,  4,  1,  3,  2,  4,  4,  2,  4,  2,  1,  4,  3,  4,  4,  2,  3,  2,  1,  3,  2,  1,  2,  1,  1,  1,  1,  3,  1,  2,  1,  1,  4,  2,  3,  1,  3,  1,  2,  3,  4,  1,  4,  2,  3,  4,  2,  3,  1,  3,  1,  1,  2,  1,  2,  1,  1,  3,  3,  3,  3,  3,  3,  4,  2,  2,  3,  3,  3,  2,  3,  2,  2,  2,  3,  2,  3,  4,  3,  3,  4,  4,  3,  2,  1,  1,  4,  3,  4,  1,  4,  3,  1,  1,  4,  1,  3,  3,  2,  3,  4,  3,  4,  4,  3,  3,  1,  1,  1,  1,  4,  4,  1,  4,  1,  2
    };
    public String getQuestion(int k){
        return this.mQuestions[k];
    }
    public String getOpt1(int k){
        return this.FirstOption[k];
    }
    public String getOpt2(int k){
        return this.SecondOption[k];
    }
    public String getOpt3(int k){
        return this.ThirdOption[k];
    }
    public String getOpt4(int k){
        return this.FourthOption[k];
    }
    public int getAns(int k)
    {
        return this.CorrectAns[k];
    }
}